# Copyright 2005 Google Inc. All Rights Reserved.
#
# Makefile for resampler_tools 
#


LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
	fir.cpp

LOCAL_TARGET := fir

include $(BUILD_HOST_EXECUTABLE)


